# put the port for the proxy to listen on here
port: 3000
# put a target URL here (or leave blank for dummy target server)
target:
# put the JWT public key here
#   e2e:        https://login.e2e.apigee.net/token_key
#   production: https://login.apigee.com/token_key (this key is production)
public_key: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0w+/0m5ENuLEAUxPxTMm
  XrJ8bhkyPunC2VCLTaA+2dkYhR0pfPM4RtCO9tqkjc63Raos3OTph9I9gE7RMBiU
  0GVMBDYe74OLZjpGeI7OO8TmQhaOeLzX/ej9QBvq1gbhHt1QGP3m43/g1bN64Ggt
  Bq4NCXm1Ie80NvdxWDsKifhYi4fgo+zhcMBaSE2Hhyc3TIg1oEKfh+EmHL/4LhPd
  7CYl4PxqR+DVNbJrdGeGOteWX4p5sW79t/8CsnvJ4St5Yv3sGK5JuBbmGiKW8wWE
  n+9bDg5i3SPlimMBdySH+wMbFULyfVSvJHeMmEAMHKDq+PVGdM+znNkPCCVIkHZG
  RQIDAQAB
  -----END PUBLIC KEY-----
# put your SSO OAuth configuration here (these URLs are production)
oauth:
  clientID: REPLACE
  clientSecret: REPLACE
  authorizationURL: https://login.apigee.net/oauth/authorize
  tokenURL: https://login.apigee.net/oauth/token
  callbackURL: http://localhost:3000/auth/sso/callback
