edgemicro:
  # put the port for the proxy to listen on here
  port: 3000
  logging:
    level: 'warn'
proxies:
- base_path: '/'
  # put a target URL here (or leave blank for dummy target server)
  url:
sso:
  # used to retrieve public key on startup if public_key isn't specified directly
  #   e2e:        https://login.e2e.apigee.net/token_key
  #   production: https://login.apigee.com/token_key
  public_key_url: https://login.e2e.apigee.net/token_key
  # put the JWT public key here to avoid request at startup
  #   note: the key below is the current production key as of this moment
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuM71moVIzpiBY+bZ/H93
    YuGwi44e6SHmtvX/bl0B1Bqzv1Yc9TrxkS7TS60QaUc3VyCZnBrfnEIBo9u6NL3R
    p+Yon+K0ZN1qJsEA8O6H7KBND7aTs5ml95/QyNqFZnDvRtKcchkenPgz0H/qjBuC
    1T9givsoy3CLgT+mdQRU3lama6pdCo+F3mTmH1woq8mIvWjUTsrAbPDWO3Uw/BuA
    7rvn4TDqTyEm8HvwFW+bZ1w7X/9kfFdQvR6l0sZh2LXtK57asq/Py+b/l1SFzMd6
    enkEFJ6Em8qOZ0pITGr97rb2sH4/rfekmIRp78rjkWcrKnoCgDqjHbEW/QHkb/9p
    kwIDAQAB
    -----END PUBLIC KEY-----
  # put your SSO OAuth configuration here (these URLs are for Apigee production)
  oauth:
    clientID: REPLACE
    clientSecret: REPLACE
    authorizationURL: https://login.e2e.apigee.net/oauth/authorize
    tokenURL: https://login.e2e.apigee.net/oauth/token
    callbackURL: http://localhost:3000/auth/sso/callback
