edgemicro:
  port: 0
  logging:
    level: 'warn'
proxies:
- base_path: '/'
  url:
sso:
  public_key:
  oauth:
    clientID: id
    clientSecret: secret
    authorizationURL: http://localhost:XXXX/oauth/authorize
    tokenURL: http://localhost:XXXX/oauth/token
    callbackURL: http://localhost:XXXX/auth/sso/callback
